### ISSUE TITLE
训练时间过长

### ISSUE THREAD

**Issue by Lee-qiangzee** [yuzhong-deng/graphcpg#1]
您好，感谢您的工作。我在尝试复现该作品的时候遇到了问题，在同等规格的GPU上graphcpg训练一轮约六个小时，而CpG Transformer仅需十几分钟，与文中报告的完全不符，请问是什么原因呢？

**Comment by yuzhong-deng** [comment]
您好，很高兴您对我们之前的工作感兴趣。同样的数据不应该有如此大的差别，您可以从gpu和cpu两方面检查，gpu方面的话graphcpg能够取到很大的batch size节省训练时间，cpu方面的话由于graphcpg会提取subgraph可能需要配置更多线程。

**Comment by Lee-qiangzee** [comment]
> 您好，很高兴您对我们之前的工作感兴趣。同样的数据不应该有如此大的差别，您可以从gpu和cpu两方面检查，gpu方面的话graphcpg能够取到很大的batch size节省训练时间，cpu方面的话由于graphcpg会提取subgraph可能需要配置更多线程。

感谢回复，我使用的数据集是HCC，按照补充文件的配置batch_size为5120 n_workers默认为12，同时尝试了batch_size为10240n_workers为16 32 64等配置但均无明显改善。
![839b478e8c2e22fcadd07ba945a4027](https://github.com/yuzhong-deng/graphcpg/assets/139248655/85451bb3-18cb-41a3-9069-8855b19ddcdc)

**Comment by yuzhong-deng** [comment]
您好，HCC数据集上一个epoch的话3分钟左右loss=0.23应该已经收敛得差不多了，validation完validation auroc能到96.9的样子，这边cpu是12代i7，要不再看看呢。
![image](https://github.com/yuzhong-deng/graphcpg/assets/57375920/752d7515-2f70-43c4-bb16-4f46d3d0829d)

**Comment by Lee-qiangzee** [comment]
您好，我将您的代码和[GraphCpG_updated_selfuse](https://github.com/Mudman14/GraphCpG_updated_selfuse/tree/main)的代码综合了一下，时间终于降到了合理的区间

**Comment by Lee-qiangzee** [comment]
您好，我将您的代码和[GraphCpG_updated_selfuse](https://github.com/Mudman14/GraphCpG_updated_selfuse/tree/main)的代码综合了一下，耗时终于降到了一个合理的范围，感谢您的回复。
